### PR TITLE
US23 Test Case

### PR DESCRIPTION
**Pull request by huanhuiyinglalala**
Test cases for US23 is done, please review

### CODE REVIEW

**Comment by claris0911** [comment]
i think you accidentally put in us4 stuff in this branch, please remove :D

**Review by claris0911 — APPROVED** [review]
test case looks good, approved doc is uploaded onto the branch

**Comment by huanhuiyinglalala** [comment]
image


Since all features have been implemented for Sprint 5 and merged to main, I will begin system testing for Sprint 4 Test cases. Additionally, since the developer's code did not have a full coverage of the test cases written, this will be the first round system test performed for this US

**Review by meganpng — APPROVED** [review]
[SimpCity US23 Test Document (3 Pass 0 Fail) (1).xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8057747/SimpCity.US23.Test.Document.3.Pass.0.Fail.1.xlsx)
Approved

**Comment by huanhuiyinglalala** [comment]
Approval is required by the SCRUM master for UAT testing in regards the team.

**Review by meganpng — APPROVED** [review]
Approved as stated in the commit message of the uploaded UAT document. Scrum Master will be approving on behalfed of the team as mentioned in the commit message of the uploaded UAT document.

**Pull request closed without merging**
