### PR TITLE
US10-TestCase

### PR DESCRIPTION
**Pull request by huanhuiyinglalala**
US10 test case is ready for review, please review the test case.

### CODE REVIEW

**Comment by claris0911** [comment]
Have reviewed the test case, looks good

**Review by claris0911 — APPROVED** [review]
accidentally left comment instead of approving, my bad :")

**Review by claris0911 — APPROVED** [review]
[SimpCity US10 Test Document (3 Pass).xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8025275/SimpCity.US10.Test.Document.3.Pass.xlsx)
test case looks good. @meganpng can use this document to sign your approval

**Review by meganpng — APPROVED** [review]
[SimpCity.US10.Test.Document.3.Pass.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8047222/SimpCity.US10.Test.Document.3.Pass.xlsx)
Reviewed and approved

**Comment by huanhuiyinglalala** [comment]
Hi, sorry I just realise that I forget to include the whole developer team as they are present during the UAT as well, hence they have to review and approve the UAT document too. For this time round, instead of reuploading the document signature, approval from members will be requested to ensure that the act is recorded on Git Hub.

**Review by amanda-chan — APPROVED** [review]
UAT approved!

**Review by claris0911 — APPROVED** [review]
uat approved :D

**Review by meganpng — APPROVED** [review]
[SimpCity.US10 UAT.3.Pass_ScrumMasterApproved.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8055746/SimpCity.US10.UAT.3.Pass_ScrumMasterApproved.xlsx)
Approved

**Comment by meganpng** [comment]
All approved pull request will be closed

**Pull request closed without merging**
