### PR TITLE
US20 Test Scenario

### PR DESCRIPTION
**Pull request by huanhuiyinglalala**
The US20 test case is ready for review, please review.

### CODE REVIEW

**Comment by claris0911** [comment]
Can there be a more detailed descriptions under test scenario column, it will make it easier to replicate the testing process

**Review by claris0911 — APPROVED** [review]
okay looks good :)

**Comment by huanhuiyinglalala** [comment]
TDA was done, please review
[SimpCity US20 Test Case.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/7695649/SimpCity.US20.Test.Case.xlsx)

**Comment by claris0911** [comment]
Test 1 and 4-2 are failing, will ask Megan to refactor. Test 4-1 is validation portion we have not covered yet, so it shld be pass

**Comment by claris0911** [comment]
The code has been refactored, pls make the necessary changes

**Comment by huanhuiyinglalala** [comment]
[SimpCity US20 Test Case.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/7695641/SimpCity.US20.Test.Case.xlsx)
The test case is revamped after the refactor of the code, now the test case fits the US better, please review and see if it is okay for TDA.

**Comment by huanhuiyinglalala** [comment]
[SimpCity US20 Test Case.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/7695683/SimpCity.US20.Test.Case.xlsx)
TDA is done for the US20, please review.

**Review by claris0911 — APPROVED** [review]
Yep thank you for updating it 👍

**Review by claris0911 — APPROVED** [review]
Ye  looks good thank you

**Review by meganpng — APPROVED** [review]
[SimpCity US20 Test Case.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/7696590/SimpCity.US20.Test.Case.xlsx)

Approval of test cases US20 with signature, looks good but fix spelling error next Sprint

**Comment by huanhuiyinglalala** [comment]
[SimpCity.US20.Test.Case.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/7697332/SimpCity.US20.Test.Case.xlsx)
UAT is done and approved by the QA, scrum master and tech lead please review.

**Comment by claris0911** [comment]
Reviewed and signed
[SimpCity.US20.Test.Case (2).xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/7697338/SimpCity.US20.Test.Case.2.xlsx)

**Review by claris0911 — APPROVED** [review]

**Review by meganpng — APPROVED** [review]
[SimpCity.US20.Test.Case.2.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/7697416/SimpCity.US20.Test.Case.2.xlsx)

Reviewed and signed

**Pull request closed without merging**
