### PR TITLE
US13 test scenarios

### PR DESCRIPTION
**Pull request by huanhuiyinglalala**
System testing for US13 is done, please review, sorry for the delay in upload, was trying to figure out how to automate the workflow before then and realize that it was not possible, hence testing came in late.

### CODE REVIEW

**Comment by huanhuiyinglalala** [comment]
image
Since all features have been implemented for Sprint 5 and merged to main, I will begin the second round of system testing for Sprint 4 Test cases.

**Comment by huanhuiyinglalala** [comment]
Sorry, the wrong pull request is open, this pull reuqest will be closed.

**Comment by huanhuiyinglalala** [comment]
image
Since all features have been implemented for Sprint 5 and merged to main, I will begin system testing for Sprint 5 Test cases once approval is given

**Review by claris0911 — APPROVED** [review]
approved doc in the branch

**Comment by huanhuiyinglalala** [comment]
Approval is required by the SCRUM master for UAT testing in regards the team.

**Review by meganpng — APPROVED** [review]
[SimpCity US13 Test Document(3 Pass 0 Fail).xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8058107/SimpCity.US13.Test.Document.3.Pass.0.Fail.xlsx)
Approved by SCRUM Master and Tech Lead System Testing

**Review by meganpng — APPROVED** [review]
Approved as stated in the commit message of the uploaded UAT document. Scrum Master will be approving on behalf of the team as mentioned in the commit message of the uploaded UAT document.

**Pull request closed without merging**
