### PR TITLE
US1 Test Scenarios

### PR DESCRIPTION
**Pull request by huanhuiyinglalala**
The test case of US5 is ready for review, please review.

### CODE REVIEW

**Comment by claris0911** [comment]
Can there be a more detailed descriptions under test scenario column, it will make it easier to replicate the testing process

**Review by claris0911 — APPROVED** [review]
looks okay, you can proceed to do TDA

**Comment by huanhuiyinglalala** [comment]
Sorry, wrong file was uploaded

[SimpCity US1 Test Case.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/7693726/SimpCity.US1.Test.Case.xlsx)

**Comment by claris0911** [comment]
3-1 should pass since we have not implemented the validation portion of it

**Comment by huanhuiyinglalala** [comment]
[SimpCity US1 Test Case.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/7693853/SimpCity.US1.Test.Case.xlsx)
The test document is fixed.

**Review by claris0911 — APPROVED** [review]
yup, looks okay thank you :) 👍

**Review by meganpng — APPROVED** [review]
Looks good!

**Comment by meganpng** [comment]
[SimpCity.US1.Test.Case.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/7696556/SimpCity.US1.Test.Case.xlsx)

Signature in Excel Sheet to show approval

**Comment by huanhuiyinglalala** [comment]
[SimpCity.US1.Test.Case.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/7697327/SimpCity.US1.Test.Case.xlsx)
UAT is done and approved by the QA, scrum master and tech lead please review.

**Comment by claris0911** [comment]
Reviewed and signed :) 
[SimpCity.US9.Test.Cases (2).xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/7697336/SimpCity.US9.Test.Cases.2.xlsx)
[SimpCity.US1.Test.Case.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/7697335/SimpCity.US1.Test.Case.xlsx)

**Review by claris0911 — APPROVED** [review]

**Review by meganpng — APPROVED** [review]
[SimpCity.US1.Test.Case.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/7697421/SimpCity.US1.Test.Case.xlsx)

Reviewed and signed

**Pull request closed without merging**
