### PR TITLE
Us2&16 test scenarios

### PR DESCRIPTION
**Pull request by huanhuiyinglalala**
image
Thanks for the update, will proceed with system testing.

### CODE REVIEW

**Comment by claris0911** [comment]
the users dont get to choose the save file, they are forced to a file. please make updates :>

**Comment by huanhuiyinglalala** [comment]
Ok sure, updates will be shown in second round of testing

**Review by claris0911 — APPROVED** [review]
approved doc is in the branch

**Comment by huanhuiyinglalala** [comment]
image
Since all features have been implemented for Sprint 5 and merged to main, I will begin system testing for Sprint 5 Test cases.

**Review by meganpng — APPROVED** [review]
[SimpCity US2 &16 Test Document (3cPass 0 Fail) (1).xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8057740/SimpCity.US2.16.Test.Document.3cPass.0.Fail.1.xlsx)
Approved

**Comment by huanhuiyinglalala** [comment]
Approval is required by the SCRUM master for UAT testing in regards the team.

**Review by meganpng — APPROVED** [review]
Approved as stated in the commit message of the uploaded UAT document. Scrum Master will be approving on behalfed of the team as mentioned in the commit message of the uploaded UAT document.

**Pull request closed without merging**
