### PR TITLE
US24 Test Case

### PR DESCRIPTION
**Pull request by huanhuiyinglalala**
Test cases for US24 are done, please review.

### CODE REVIEW

**Review by claris0911 — APPROVED** [review]
test case looks good, approved doc is uploaded onto the branch

**Comment by huanhuiyinglalala** [comment]
image
Since all features have been implemented for Sprint 5 and merged to main, I will begin system testing for Sprint 5 Test cases.

**Review by meganpng — APPROVED** [review]
[SimpCity US24 Test Document (3 Pass 1 Nil) (1).xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8057758/SimpCity.US24.Test.Document.3.Pass.1.Nil.1.xlsx)
Approved

**Comment by huanhuiyinglalala** [comment]
Approval is required by the SCRUM master for UAT testing in regards the team.

**Review by meganpng — APPROVED** [review]
Approved as stated in the commit message of the uploaded UAT document. Scrum Master will be approving on behalf of the team as mentioned in the commit message of the uploaded UAT document.

**Pull request closed without merging**
