### PR TITLE
US17-TestCase

### PR DESCRIPTION
**Pull request by huanhuiyinglalala**
US17 is ready for review, please review. Sorry for not uploading it in time, accidentally missed it while uploading the rest of the test cases. Thanks to the team for indirectly reminding me.

### CODE REVIEW

**Comment by huanhuiyinglalala** [comment]
System testing for US17 is done,  please review, sorry for the delay in upload, was trying to figure out how to automate the workflow before then and realize that it was not possible, hence testing came in late. 

Please review US17 and fill up the developer response under the remarks column.

**Comment by claris0911** [comment]
you uploaded US7 test case in the wrong branch

**Review by claris0911 — APPROVED** [review]
accidentally left comment instead of approving, my bad :")

**Comment by huanhuiyinglalala** [comment]
The wrong document is deleted, will commit a new document.

**Comment by claris0911** [comment]
[SimpCity US17 Test Document (2 Pass 1 Fail).xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8025232/SimpCity.US17.Test.Document.2.Pass.1.Fail.xlsx)

Have updated the remarks with developers response. Otherwise, it looks okay. @meganpng can use this doc to sign approval

**Review by claris0911 — APPROVED** [review]
developers response has been updated, otherwise it all looks okay

**Comment by huanhuiyinglalala** [comment]
ok thank you for updating

**Review by meganpng — APPROVED** [review]
[SimpCity.US17.Test.Document.2.Pass.1.Fail.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8047239/SimpCity.US17.Test.Document.2.Pass.1.Fail.xlsx)
Approved

**Comment by claris0911** [comment]
sorry, could you please make an update.
After discussion the team has decided that we shld only accept upper case "Y" for the user input. Please make the changes accordingly thank you <3

**Comment by huanhuiyinglalala** [comment]
ok sure, no problem, however, I realise that my test coverage did not test for what is stated, hence the previous test case do not need to retest, sorry that my test does not have a full coverage of all the instances. Will take note next time.

**Comment by huanhuiyinglalala** [comment]
image

Since all features have been implemented for Sprint 5 and merged to main, I will begin the second round of system testing for Sprint 3 Test cases.

**Review by claris0911 — APPROVED** [review]
files added to the branch :3

**Review by meganpng — APPROVED** [review]
[SimpCity US17 Test Document (3 Pass 0 Fail).xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8056479/SimpCity.US17.Test.Document.3.Pass.0.Fail.xlsx)
Approved

**Comment by huanhuiyinglalala** [comment]
Approval is required by the SCRUM master for UAT testing in regards the team.

**Review by meganpng — APPROVED** [review]
Approved as stated in the commit message of the uploaded UAT document.

**Pull request closed without merging**
