### PR TITLE
US5 Test Scenarios

### PR DESCRIPTION
**Pull request by huanhuiyinglalala**
Test case for US5 is ready for review, please review.

### CODE REVIEW

**Comment by claris0911** [comment]
options 3,4,5 is not relevant for this user story, could you remove it

**Review by claris0911 — APPROVED** [review]
continue on with TDA 😄

**Comment by huanhuiyinglalala** [comment]
TDA was done for US5, please review
[SimpCity US5Test Cases.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/7693731/SimpCity.US5Test.Cases.xlsx)

**Comment by claris0911** [comment]
3-1 is being refactored by Megan, 3-2 is a validation portion we have not covered, so it shld be passing

**Comment by huanhuiyinglalala** [comment]
ok noted, this is the one that is corrected, the testing for Megan's portion I will upload it again
[SimpCity US5Test Cases.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/7693972/SimpCity.US5Test.Cases.xlsx)
.

**Comment by claris0911** [comment]
code has been refactored, pls redo TDA 😭

**Comment by huanhuiyinglalala** [comment]
[SimpCity US5Test Cases.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/7695387/SimpCity.US5Test.Cases.xlsx)
Sorry, the wrong version was uploaded. this is the correct one

**Review by claris0911 — APPROVED** [review]
yep is okay, thanks for doing this 3 times <3

**Review by meganpng — APPROVED** [review]
[SimpCity US5Test Cases.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/7696569/SimpCity.US5Test.Cases.xlsx)

Looks good, but has spelling error, metion instead of mentioned, please change in future Sprint, thanks

**Comment by huanhuiyinglalala** [comment]
[SimpCity.US5Test.Cases.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/7697331/SimpCity.US5Test.Cases.xlsx)
UAT is done and approved by the QA, scrum master and tech lead please review.

**Comment by claris0911** [comment]
Reviewed and signed 
[Uploading SimpCity.US5Test.Cases (1).xlsx…]()

**Review by claris0911 — APPROVED** [review]

**Review by meganpng — APPROVED** [review]
[SimpCity.US5Test.Cases (1).xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/7697402/SimpCity.US5Test.Cases.1.xlsx)

Reviewed and signed UAT

**Pull request closed without merging**
