### PR TITLE
US12-TestCases

### PR DESCRIPTION
**Pull request by huanhuiyinglalala**
Please review US12 test case before I moved on to the test script.

### CODE REVIEW

**Comment by claris0911** [comment]
Have reviewed the test case, looks good

**Review by claris0911 — APPROVED** [review]
accidentally left comment instead of approving, my bad :")

**Review by claris0911 — APPROVED** [review]
[SimpCity US12 Test Document (2 Pass).xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8025311/SimpCity.US12.Test.Document.2.Pass.xlsx)
test case looks good. @meganpng can use this doc to do your approval

**Review by meganpng — APPROVED** [review]
[SimpCity.US12.Test.Document.2.Pass.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8043228/SimpCity.US12.Test.Document.2.Pass.xlsx)

Reviewed and approved

**Comment by huanhuiyinglalala** [comment]
UAT for US12 was done, but has not been recorded by git yet, to ensure that it is recorded, \Tech Lead and SCRUM Master please review, sign and approve if everything is okay.

**Comment by huanhuiyinglalala** [comment]
Hi, sorry I just realise that I forget to include the whole developer team as they are present during the UAT as well, hence they have to review and approve the UAT document too. For this time round, instead of reuploading the document signature, approval from members will be re-requested to ensure that the act is recorded on Git Hub.

**Review by claris0911 — APPROVED** [review]
[SimpCity.US12.UAT.2.Pass.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8055354/SimpCity.US12.UAT.2.Pass.xlsx)
UAT looks good, @meganpng @amanda-chan  can use this doc for approval

**Review by amanda-chan — APPROVED** [review]
UAT approved!

**Review by meganpng — APPROVED** [review]
[SimpCity.US12.UAT.2.Pass_ScrumMasterApproved.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8055762/SimpCity.US12.UAT.2.Pass_ScrumMasterApproved.xlsx)
Approved

**Comment by meganpng** [comment]
All approved pull request will be closed

**Pull request closed without merging**
