### PR TITLE
Us3 test scenarios

### PR DESCRIPTION
**Pull request by huanhuiyinglalala**
image
Since all features have been implemented for Sprint 5 and merged to main, I will begin system testing for Sprint 5 Test cases once approval is received

### CODE REVIEW

**Review by claris0911 — APPROVED** [review]
system tests approved. Approved doc is uploaded on the branch

**Review by meganpng — APPROVED** [review]
[SimpCity US3 Test Document (3 Pass 0 Fail) (1).xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8057741/SimpCity.US3.Test.Document.3.Pass.0.Fail.1.xlsx)
Approved

**Comment by huanhuiyinglalala** [comment]
Approval is required by the SCRUM master for UAT testing in regards the team.

**Review by meganpng — APPROVED** [review]
Approved as stated in the commit message of the uploaded UAT document. Scrum Master will be approving on behalfed of the team as mentioned in the commit message of the uploaded UAT document.

**Pull request closed without merging**
