### PR TITLE
US21 Test Scenarios

### PR DESCRIPTION
**Pull request by amanda-chan**
Please check if the test scenarios are okay

### CODE REVIEW

**Review by claris0911 — APPROVED** [review]
Test scenario covers all aspects of US21. Looks good 👍 :)

**Comment by amanda-chan** [comment]
Please review if the test scenario results are okay

[TestScenarios_US 21 (Results).xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/7682988/TestScenarios_US.21.Results.xlsx)

**Comment by amanda-chan** [comment]
Please review if the test results for the scenarios are okay

**Comment by claris0911** [comment]
testing was done before all codes are consolidates, pls retest it again

**Comment by amanda-chan** [comment]
Sure will test again once the merge on the main branch is complete

**Comment by claris0911** [comment]
Thank you looks good, have approved in the doc :) 
[TestScenarios_US 21 (Results).xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/7693927/TestScenarios_US.21.Results.xlsx)

**Review by claris0911 — APPROVED** [review]
👍

**Comment by meganpng** [comment]
[TestScenarios_US.21.Results (1).xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/7696549/TestScenarios_US.21.Results.1.xlsx)

Reviewed the testing, looks good, approved

**Review by meganpng — APPROVED** [review]
Approved, file in comment

**Comment by meganpng** [comment]
Branch is closed by accident, reopened

**Comment by amanda-chan** [comment]
UAT is done and approved by the QA, Scrum Master @meganpng  and Tech Lead @claris0911 please review, thanks!

[TestScenarios_US21 Results.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/7697323/TestScenarios_US21.Results.xlsx)

**Comment by claris0911** [comment]
Reviewed and signed :)
[TestScenarios_US21.Results.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/7697339/TestScenarios_US21.Results.xlsx)

**Review by claris0911 — APPROVED** [review]

**Review by meganpng — APPROVED** [review]
[TestScenarios_US21.Results.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/7697387/TestScenarios_US21.Results.xlsx)
Reviewed and signed for UAT

**Pull request closed without merging**
