### PR TITLE
US14 Test Case

### PR DESCRIPTION
**Pull request by huanhuiyinglalala**
System testing for US14 is done, please review, sorry for the delay in upload, was trying out how to automate test scripts and celebrate Chinese New Year. I got too caught up with this stuff and forget to upload my test cases.

### CODE REVIEW

**Review by claris0911 — APPROVED** [review]
test case looks good. have uploaded the doc with the approval in the branch

**Comment by huanhuiyinglalala** [comment]
Sorry for the accidental click, will be more cautious in the future.

**Review by claris0911 — APPROVED** [review]
[SimpCity US14 Test Document (2 Pass 1 Fail).xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8055378/SimpCity.US14.Test.Document.2.Pass.1.Fail.xlsx)
looks good, need to rmb to update when sprint 5 stuff is merged
@meganpng can use this doc to give approval

**Review by meganpng — APPROVED** [review]
[SimpCity.US14.Test.Document.2.Pass.1.Fail.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8056405/SimpCity.US14.Test.Document.2.Pass.1.Fail.xlsx)
Approved

**Comment by huanhuiyinglalala** [comment]
image
Since all features have been implemented for Sprint 5 and merged to main, I will begin the second round of system testing for Sprint 4 Failed Test cases.

**Comment by huanhuiyinglalala** [comment]
Approval is required by the SCRUM master for UAT testing in regards the team.

**Comment by meganpng** [comment]
Approval was done behalfed of the scrum master, hence review approve from Tech Lead is not required anymore

**Review by meganpng — APPROVED** [review]
Approved as stated in the commit message of the uploaded UAT document.

**Pull request closed without merging**
