### PR TITLE
US9 Test Scenarios

### PR DESCRIPTION
**Pull request by huanhuiyinglalala**
The test case for US9 is done, please review.

### CODE REVIEW

**Comment by huanhuiyinglalala** [comment]
Sorry I have upload the wrong file, allow me to upload it again �
[SimpCity US9 Test Cases.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/7694885/SimpCity.US9.Test.Cases.xlsx)
�

**Review by claris0911 — APPROVED** [review]
looks good

**Review by meganpng — APPROVED** [review]
[SimpCity US9 Test Cases.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/7696575/SimpCity.US9.Test.Cases.xlsx)

Reviewed and approved with signature

**Review by claris0911 — APPROVED** [review]
Yep looks good :D

**Comment by huanhuiyinglalala** [comment]
[SimpCity.US9.Test.Cases.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/7697322/SimpCity.US9.Test.Cases.xlsx)
UAT is done and approved by the QA, scrum master and tech lead please review.

**Comment by claris0911** [comment]
Done reviewing and signed
[SimpCity.US9.Test.Cases (2).xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/7697334/SimpCity.US9.Test.Cases.2.xlsx)

**Review by claris0911 — APPROVED** [review]

**Review by meganpng — APPROVED** [review]
[SimpCity.US9.Test.Cases.2.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/7697405/SimpCity.US9.Test.Cases.2.xlsx)

Reviewed and signed

**Pull request closed without merging**
