### PR TITLE
US11 Test Cases

### PR DESCRIPTION
**Pull request by huanhuiyinglalala**
System testing for US11 is done, please review, sorry for the delay in upload, was trying out how to automate test scripts and celebrate Chinese New Year. I got too caught up with this stuff and forget to upload my test cases.

### CODE REVIEW

**Review by claris0911 — APPROVED** [review]
test case looks good. have uploaded the document with the approval.

**Comment by huanhuiyinglalala** [comment]
Sorry for the accidental click, will be more cautious in the future.

**Review by claris0911 — APPROVED** [review]
[SimpCity US11 Test Document (2 Pass 1 Fail).xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8055362/SimpCity.US11.Test.Document.2.Pass.1.Fail.xlsx)
looks okay, need to rmb to update when all the things are merged for sprint 5
@meganpng can use this doc to do approval

**Comment by huanhuiyinglalala** [comment]
image
Since all features have been implemented for Sprint 5 and merged to main, I will begin the second round of system testing for Sprint 4 Test cases.

**Review by meganpng — APPROVED** [review]
[SimpCity.US11.Test.Document.2.Pass.1.Fail.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8056393/SimpCity.US11.Test.Document.2.Pass.1.Fail.xlsx)
Approved

**Comment by huanhuiyinglalala** [comment]
image
Sorry, have forgotten to indicate that all features was implemented already which allow me to do the test.

**Review by claris0911 — APPROVED** [review]
system test approved, doc uploaded in the branch

**Comment by huanhuiyinglalala** [comment]
Approval is required by the SCRUM master for UAT testing in regards the team.

**Review by meganpng — APPROVED** [review]
Approved as stated in the commit message of the uploaded UAT document.

**Pull request closed without merging**
