### PR TITLE
US6-Test Cases

### PR DESCRIPTION
**Pull request by huanhuiyinglalala**
This is US6 test cases.

### CODE REVIEW

**Comment by claris0911** [comment]
Have reviewed the test case, it looks okay

**Review by claris0911 — APPROVED** [review]
accidentally left comment instead of approving, my bad :")

**Review by claris0911 — APPROVED** [review]
[SimpCity US6 Test Document (5 Pass).xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8025386/SimpCity.US6.Test.Document.5.Pass.xlsx)
results looks good. @meganpng can use this doc to sign ur approval

**Review by meganpng — APPROVED** [review]
[SimpCity.US6.Test.Document.5.Pass.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8042929/SimpCity.US6.Test.Document.5.Pass.xlsx)

Reviewed and it looks good, approved

**Comment by huanhuiyinglalala** [comment]
UAT for US6 was done, but has not been recorded by git yet, to ensure that it is recorded, i request the Tech Lead and SCRUM Master to review, approve and sign.

**Comment by huanhuiyinglalala** [comment]
Hi, sorry I just realise that I forget to include the whole developer team as they are present during the UAT as well, hence they have to review and approve the UAT document too. For this time round, instead of reuploading the document signature, approval from members will be requested to ensure that the act is recorded on Git Hub.

**Review by claris0911 — APPROVED** [review]
[SimpCity.US6.Test.Document.5.Pass.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8055322/SimpCity.US6.Test.Document.5.Pass.xlsx)
UAT looks good, @amanda-chan @meganpng can use this doc to give approval

**Review by amanda-chan — APPROVED** [review]
Have approved!

**Review by meganpng — APPROVED** [review]
[SimpCity.US6.Test.Document.5.Pass_ScrumMasterApproved.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8055721/SimpCity.US6.Test.Document.5.Pass_ScrumMasterApproved.xlsx)
Approved

**Comment by meganpng** [comment]
All approved pull request will be closed

**Pull request closed without merging**
