### PR TITLE
US19 Test Cases

### PR DESCRIPTION
**Pull request by huanhuiyinglalala**
US19 test cases that is pushed back from sprint 4 is done in sprint 5, please review

### CODE REVIEW

**Comment by claris0911** [comment]
for 1-test values-step 4, Y/N is not clearly stated

**Comment by huanhuiyinglalala** [comment]
I have corrected the test cases, please review it again

**Review by claris0911 — APPROVED** [review]
test case looks good, approved doc is uploaded into the branch

**Comment by huanhuiyinglalala** [comment]
image
Since all features have been implemented for Sprint 5 and merged to main, I will begin system testing for Sprint 5 Test cases.

**Review by meganpng — APPROVED** [review]
[SimpCity US19 Test Document (4 Pass 0 Fail) (1).xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8057755/SimpCity.US19.Test.Document.4.Pass.0.Fail.1.xlsx)
Approved

**Comment by huanhuiyinglalala** [comment]
Approval is required by the SCRUM master for UAT testing in regards the team.

**Review by meganpng — APPROVED** [review]
Approved as stated in the commit message of the uploaded UAT document. Approval from tech lead is not required as scrum master will be doing on behalfed

**Pull request closed without merging**
