### PR TITLE
US22 Test Case

### PR DESCRIPTION
**Pull request by huanhuiyinglalala**
System testing for US22 is done, please review, sorry for the delay in upload, was trying out how to automate test scripts and celebrate Chinese New Year. I got too caught up with this stuff and forget to upload my test cases.

### CODE REVIEW

**Review by claris0911 — APPROVED** [review]
test case looks good. have uploaded the doc with the approval in the branch

**Review by claris0911 — APPROVED** [review]
[SimpCity US22 Test Document (1 Pass 2 Fail).xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8055381/SimpCity.US22.Test.Document.1.Pass.2.Fail.xlsx)
looks good, will implement the extra validation and need to rmb to update this when the features are implemented
@meganpng can use this doc to do approval

**Review by meganpng — APPROVED** [review]
[SimpCity.US22.Test.Document.1.Pass.2.Fail.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8056408/SimpCity.US22.Test.Document.1.Pass.2.Fail.xlsx)
Approved

**Comment by huanhuiyinglalala** [comment]
image
Since all features have been implemented for Sprint 5 and merged to main, I will begin the second round of system testing for Sprint 4 Test cases.

**Review by claris0911 — APPROVED** [review]
approved doc on the branch <3

**Comment by huanhuiyinglalala** [comment]
sorry for forgetting to ask for re-reviwer, @claris0911 , thanks for doing that

**Comment by huanhuiyinglalala** [comment]
Approval is required by the SCRUM master for UAT testing in regards the team.

**Review by meganpng — APPROVED** [review]
Approved as stated in the commit message of the uploaded UAT document.

**Pull request closed without merging**
