### PR TITLE
US15 Test Case

### PR DESCRIPTION
**Pull request by huanhuiyinglalala**
System testing for US15 is done, please review, sorry for the delay in upload, was trying out how to automate test scripts and celebrate Chinese New Year. I got too caught up with this stuff and forget to upload my test cases.

### CODE REVIEW

**Comment by claris0911** [comment]
there seems to be a typo in test 2,  test values. 
original: "--> your choice? 4"
typo corrected: "--> your choice? 1"

**Review by claris0911 — APPROVED** [review]
there is a typo in the test case as stated in the comment (https://github.com/huanhuiyinglalala/SimpCityQA/pull/18#issuecomment-1032853176). otherwise, it looks good :)

**Comment by huanhuiyinglalala** [comment]
image
Since all features have been implemented for Sprint 5 and merged to main, I will begin system testing for Sprint 5 Test cases.

**Review by meganpng — APPROVED** [review]
[SimpCity US15 Test Case (Checked)_System_Testing.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8057910/SimpCity.US15.Test.Case.Checked._System_Testing.xlsx)
Approved by Tech Lead and SCRUM Master

**Review by claris0911 — APPROVED** [review]
approved with megan <3

**Comment by huanhuiyinglalala** [comment]
Approval is required by the SCRUM master for UAT testing in regards the team.

**Review by meganpng — APPROVED** [review]
Approved as stated in the commit message of the uploaded UAT document.

**Pull request closed without merging**
