### PR TITLE
US7-TestCases

### PR DESCRIPTION
**Pull request by huanhuiyinglalala**
Please review test case 7 before I move on to the test script.

### CODE REVIEW

**Comment by huanhuiyinglalala** [comment]
Hi, I have refined the US7 test case, please review the latest one instead.

**Comment by claris0911** [comment]
Have reviewed the test case, it looks good

**Comment by huanhuiyinglalala** [comment]
Testing for US7 is done, however, some test cases failed due to some features not being implemented in Sprint 3. Please review. Thank You.

System testing for US7 is done,  please review, sorry for the delay in upload, was trying to figure out how to automate the workflow before then and realize that it was not possible, hence testing came in late.

**Comment by claris0911** [comment]
[SimpCity US7 Test Document (1 Pass 2 Fail) (1).xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8024446/SimpCity.US7.Test.Document.1.Pass.2.Fail.1.xlsx)

system testing results look okay as of sprint 3's progress. Megan can add your signature using this reuploaded doc

**Review by claris0911 — APPROVED** [review]
system testing looks good as of sprint 3's progress

**Review by meganpng — APPROVED** [review]
[SimpCity.US7.Test.Document.1.Pass.2.Fail.1.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8043012/SimpCity.US7.Test.Document.1.Pass.2.Fail.1.xlsx)

Reviewed and approved

**Comment by huanhuiyinglalala** [comment]
Thank for reviewing, another round of system testing will be performed in sprint 5 to ensure that all test scenario passes before moving on to UAT.

**Comment by huanhuiyinglalala** [comment]
Since the feature, US2 Save game progress, US15 Check the current score, US14 Check remaining building has not been implemented yet as of sprint 3, moreover, US17 Return to the main menu at any point of the 16 round as well as US18 confirm exiting the game.
Therefore, another round of system testing will be performed in sprint 5 where the feature will be developed to ensure that all test scenario passes before moving on to UAT.

**Comment by claris0911** [comment]
sorry, could you please make an update.
After discussion the team has decided that we shld only accept upper case "Y" for the user input. Please make the changes accordingly thank you <3

**Comment by huanhuiyinglalala** [comment]
image
Since all features have been implemented for Sprint 5 and merged to main, I will start the second round of testing.

**Comment by huanhuiyinglalala** [comment]
> sorry, could you please make an update. After discussion the team has decided that we shld only accept upper case "Y" for the user input. Please make the changes accordingly thank you <3

update will be made in the following test

**Review by meganpng — APPROVED** [review]
[SimpCity US7 Test Document V2 (3 Pass 0 Fail).xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8056464/SimpCity.US7.Test.Document.V2.3.Pass.0.Fail.xlsx)
Approved

**Comment by huanhuiyinglalala** [comment]
Approval is required by the SCRUM master for UAT testing in regards the team.

**Review by meganpng — APPROVED** [review]
Approved as stated in the commit message of the uploaded UAT document.

**Pull request closed without merging**
