### PR TITLE
US8-TestCase

### PR DESCRIPTION
**Pull request by huanhuiyinglalala**

### CODE REVIEW

**Comment by huanhuiyinglalala** [comment]
Hi, I have refined the US8 test case, please review the latest one instead.

**Comment by claris0911** [comment]
Have reviewed the test case, it looks okay

**Review by claris0911 — APPROVED** [review]
accidentally left comment instead of approving, my bad :")

**Review by claris0911 — APPROVED** [review]
[SimpCity US8 Test Document (4 Pass).xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8025368/SimpCity.US8.Test.Document.4.Pass.xlsx)
test case looks good. @meganpng use this doc to do approval

**Review by meganpng — APPROVED** [review]
[SimpCity.US8.Test.Document.4.Pass.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8043153/SimpCity.US8.Test.Document.4.Pass.xlsx)

Reviewed and approved

**Review by huanhuiyinglalala — COMMENTED** [review]
Sorry, it was suppose UAT US8 instead of US6 was done, sorry the wrong commit message, I hope that it was rectified in time to advise confusion.

**Comment by huanhuiyinglalala** [comment]
UAT for USu was done, but has not been recorded by git yet, to ensure that it is recorded, \Tech Lead and SCRUM Master please review, sign and approve if everything is okay.

**Comment by huanhuiyinglalala** [comment]
Hi, sorry I just realise that I forget to include the whole developer team as they are present during the UAT as well, hence they have to review and approve the UAT document too. For this time round, instead of reuploading the document signature, approval from members will be requested to ensure that the act is recorded on Git Hub.

**Comment by huanhuiyinglalala** [comment]
Sorry, I have just realize that I have entered the wrong user stories in the user story column, however the whole test content is correct, will correct this minor mistake. I am glad that no one has reviewed yet.

**Review by claris0911 — APPROVED** [review]
[SimpCity.US8.UAT.4.Pass.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8055336/SimpCity.US8.UAT.4.Pass.xlsx)
UAT signed, @meganpng can use this doc to do approval

**Comment by huanhuiyinglalala** [comment]
@amanda-chan , please use the doc and approve as well

**Review by amanda-chan — APPROVED** [review]
UAT approved!

**Review by meganpng — APPROVED** [review]
[SimpCity.US8.UAT.4.Pass_ScrumMasterApproved.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8055733/SimpCity.US8.UAT.4.Pass_ScrumMasterApproved.xlsx)
Approved

**Comment by meganpng** [comment]
All approved pull request will be closed

**Pull request closed without merging**
