### PR TITLE
US18-TestCases

### PR DESCRIPTION
**Pull request by huanhuiyinglalala**
US18 test case is ready for review, please review it so that I can move on the test scripts

### CODE REVIEW

**Comment by claris0911** [comment]
the test scenario workflow is not what Megan has coded, please make necessary changes. 
Inputting "Y" will allow the user to save the progress, then exit the game 
Inputting "N" will just exit the game

**Comment by claris0911** [comment]
Have reviewed the test case, looks good

**Review by claris0911 — APPROVED** [review]
accidentally left comment instead of approving, my bad :")

**Review by claris0911 — APPROVED** [review]
[SimpCity US18 Test Document (1 Pass 2 Fail).xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8025295/SimpCity.US18.Test.Document.1.Pass.2.Fail.xlsx)
test case looks good. @meganpng can use this doc to do your approval

**Review by meganpng — APPROVED** [review]
[SimpCity.US18.Test.Document.1.Pass.2.Fail.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8047162/SimpCity.US18.Test.Document.1.Pass.2.Fail.xlsx)

Reviewed and approved

**Comment by huanhuiyinglalala** [comment]
Thanks for reviewing, since the feature, US3 Load Save Game, US2 Save game progress, US16 Save game progress during any of the 16 rounds has not been implemented yet which causes some of the test scenarios to fail. Another round of system testing will be performed in sprint 5 where the feature will be developed to ensure that all test scenario passes before moving on to UAT.

**Comment by huanhuiyinglalala** [comment]
image

Since all features have been implemented for Sprint 5 and merged to main, I will begin the second round of system testing for Sprint 3 Test cases.

**Comment by huanhuiyinglalala** [comment]
image
Since all features have been implemented for Sprint 5 and merged to main, I will start the second round of testing.

**Review by meganpng — APPROVED** [review]
[SimpCity US18 Test Document (3 Pass 0 Fail).xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8056462/SimpCity.US18.Test.Document.3.Pass.0.Fail.xlsx)
Approved

**Comment by huanhuiyinglalala** [comment]
Approval is required by the SCRUM master for UAT testing in regards the team.

**Review by meganpng — APPROVED** [review]
Approved as stated in the commit message of the uploaded UAT document.

**Pull request closed without merging**
