### PR TITLE
US4 Test Case

### PR DESCRIPTION
**Pull request by huanhuiyinglalala**
System testing for US4 is done, please review, sorry for the delay in upload, was trying out how to automate test scripts and celebrate Chinese New Year. I got too caught up with this stuff and forget to upload my test cases.

### CODE REVIEW

**Review by claris0911 — APPROVED** [review]
test case looks good. have uploaded the doc with the approval in the branch

**Comment by huanhuiyinglalala** [comment]
Sorry for the accidental click, will be more cautious in the future.

**Comment by huanhuiyinglalala** [comment]
please review the test result, another round of testing will be done as there are failing due to the developers code did not have a full coverage of the test cases

**Review by claris0911 — APPROVED** [review]
[SimpCity US4 Test Document (1 Pass 2 Fail).xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8055370/SimpCity.US4.Test.Document.1.Pass.2.Fail.xlsx)
looks good, need to rmb to update when all things are incorporated in sprint 5
@meganpng can use this doc to give approval

**Comment by huanhuiyinglalala** [comment]
image
Since all features have been implemented for Sprint 5 and merged to main, I will begin the second round of system testing for Sprint 4 Test cases.

**Review by meganpng — APPROVED** [review]
[SimpCity.US4.Test.Document.1.Pass.2.Fail.xlsx](https://github.com/huanhuiyinglalala/SimpCityQA/files/8056372/SimpCity.US4.Test.Document.1.Pass.2.Fail.xlsx)
Approved

**Comment by huanhuiyinglalala** [comment]
image
Sorry, have forgotten to indicate that all features was implemented already which allow me to do the test.

**Review by claris0911 — APPROVED** [review]
system test approved, uploaded onto the branch

**Comment by huanhuiyinglalala** [comment]
Approval is required by the SCRUM master for UAT testing in regards the team.

**Review by meganpng — APPROVED** [review]
Approved as stated in the commit message of the uploaded UAT document.

**Pull request closed without merging**
